# Generated by Django 5.0.6 on 2024-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=6)),
                ('word', models.CharField(max_length=45)),
                ('number_of_guesses', models.IntegerField()),
                ('number_of_guesses_taken', models.IntegerField()),
                ('date_played', models.CharField()),
                ('result', models.CharField(choices=[('W', 'Won'), ('L', 'Lost')])),
            ],
        ),
    ]
