# Generated by Django 5.0.6 on 2024-06-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangmangames',
            name='number_of_guesses_taken',
        ),
        migrations.CreateModel(
            name='HangmanGuesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=45)),
                ('foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hangmangames')),
            ],
        ),
    ]
