# Generated by Django 5.0.6 on 2024-06-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_hangmangames_number_of_guesses_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangmanguesses',
            name='foreign_key',
            field=models.IntegerField(),
        ),
    ]
