# Generated by Django 5.0.6 on 2024-06-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_hangmanguesses_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hangmangames',
            name='date_played',
        ),
        migrations.RemoveField(
            model_name='hangmangames',
            name='number_of_guesses',
        ),
        migrations.RemoveField(
            model_name='hangmangames',
            name='result',
        ),
    ]
