# Generated by Django 5.0.6 on 2024-07-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tttmoves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tttmoves',
            name='player_turn',
        ),
    ]
