name: PostgreSQL Service

on:
  push:
    branches: [ "website" ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Python dependencies
        run: pip install -r requirements.txt  # Adjust as needed
      - name: Run Django tests
        run: python manage.py test  # Adjust as needed
